# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exampleSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	pod ‘Cocoa’, :path => '~/Desktop/Cocoa’
  use_frameworks!
	pod 'IQKeyboardManager'
  # Pods for exampleSDK

end
